### ISSUE TITLE
Not working in MacVim

### ISSUE THREAD

**Issue by georgebaev** [KabbAmine/vZoom.vim#1]
Hi,

Thank you for the useful plugin! It works correctly in the console Vim but it doesn't seem to work in MacVim. Could you please make it work in MacVim if possible? Thank you very much in advance!

**Comment by KabbAmine** [comment]
This is strange, the plugin uses only basic vim commands, so the behavior should be the same for all versions.

What's exactly not working for you?

**Comment by georgebaev** [comment]
I'm sorry, it's my mistake. The plugin works correctly in MacVim, I forgot to restart MacVim after installing the plugin.

**Comment by KabbAmine** [comment]
No problem :smiley:
